import { ConsultaI } from "./consulta.interface";
import { BiopsiaI } from "./biopsia.interface";
import { PacienteI } from "./paciente.interface";
import { EmpleadoI } from "./empleado.interface";
import { SucursalI } from "./sucursal.interface";
import { StatusI } from "./status.interface";
import { ServicioI } from "./servicio.interface";
import { PagoI } from "./pago.interface";
import { ProductoI } from "./producto.interface";
import { FrecuenciaI } from "./frecuencia.interface";
import { TipoCitaI } from "./tipo-cita.interface";
import { FacturaI } from "./factura.interface";
import { Document } from "mongoose";
import { FormaPagoI } from "./forma-pago.interface";
import { MedioI } from "./medio.interface";

export interface CuracionI extends Document {
    create_date: Date;
    hora_aplicacion: Date;
    fecha_hora: Date;
    consultaId: string;
    paciente: PacienteI;
    dermatologo: EmpleadoI;
    patologo: EmpleadoI;
    quien_agenda: EmpleadoI;
    quien_confirma: EmpleadoI;
    tipo_cita: TipoCitaI;
    status: StatusI;
    sucursal: SucursalI;
    consecutivo: Number;
    pagado: boolean;
    precio: string;
    pago_dermatologo: string;
    pago_patologo: string;
    total: string;
    total_aplicacion: string;
    materiales: [];
    biopsias: BiopsiaI[];
    hasBiopsia: boolean;
    costo_biopsias: string;
    servicio: ServicioI;
    factura: FacturaI;
    pagos: PagoI[];
    hora_llegada: string;
    hora_atencion: string;
    hora_salida: string;
    producto: ProductoI;
    frecuencia: FrecuenciaI;
    porcentaje_descuento_clinica: string;
    has_descuento_dermatologo: boolean;
    descuento_clinica: string;
    descuento_dermatologo: string;
    forma_pago: FormaPagoI;
    medio: MedioI;
    turno: string;
    observaciones: string;
}