import { PacienteI } from "./paciente.interface";
import { SucursalI } from "./sucursal.interface";
import { EmpleadoI } from "./empleado.interface";
import { TipoCitaI } from "./tipo-cita.interface";
import { StatusI } from "./status.interface";
import { ServicioI } from "./servicio.interface";
import { PagoI } from "./pago.interface";
import { MedioI } from "./medio.interface";
import { ProductoI } from "./producto.interface";
import { FrecuenciaI } from "./frecuencia.interface";
import { FacturaI } from "./factura.interface";
import { Document } from "mongoose";
import { FormaPagoI } from "./forma-pago.interface";

export interface DermapenI extends Document {
    create_date: Date;
    hora_aplicacion: Date;
    fecha_hora: Date;
    paciente: PacienteI;
    consultaId: String;
    dermatologo: EmpleadoI;
    servicio: ServicioI;
    tratamientos: [];
    quien_agenda: EmpleadoI;
    tipo_cita: TipoCitaI;
    medio: MedioI;
    quien_confirma_llamada: EmpleadoI;
    quien_confirma_asistencia: EmpleadoI;
    status: StatusI;
    motivos: String;
    precio: String;
    pago_dermatologo: String;
    costo: String;
    total: String;
    tiempo: String;
    observaciones: String;
    sucursal: SucursalI;
    promovendedor: EmpleadoI;
    cosmetologa: EmpleadoI;
    hora_llegada: String;
    hora_atencion: String;
    hora_salida: String;
    pagado: Boolean;
    factura: FacturaI;
    pagos: PagoI[];
    materiales: [];
    consecutivo: Number;
    producto: ProductoI;
    frecuencia: FrecuenciaI;
    total_aplicacion: String;
    porcentaje_descuento_clinica: String;
    has_descuento_dermatologo: Boolean;
    descuento_clinica: String;
    descuento_dermatologo: String;
    forma_pago: FormaPagoI;
    turno: String;
}