import { ConsultaI } from "./consulta.interface";
import { PacienteI } from "./paciente.interface";
import { EmpleadoI } from "./empleado.interface";
import { SucursalI } from "./sucursal.interface";
import { StatusI } from "./status.interface";
import { ServicioI } from "./servicio.interface";
import { PagoI } from "./pago.interface";
import { ProductoI } from "./producto.interface";
import { FrecuenciaI } from "./frecuencia.interface";
import { TipoCitaI } from "./tipo-cita.interface";
import { FacturaI } from "./factura.interface";
import { Document } from "mongoose";
import { FormaPagoI } from "./forma-pago.interface";
import { MedioI } from "./medio.interface";

export interface EsteticaI extends Document {
    create_date: Date;
    hora_aplicacion: Date;
    fecha_hora: Date;
    consultaId: string;
    paciente: PacienteI;
    dermatologo: EmpleadoI;
    promovendedor: EmpleadoI;
    cosmetologa: EmpleadoI;
    quien_agenda: EmpleadoI;
    quien_confirma: EmpleadoI;
    tipo_cita: TipoCitaI;
    pago_dermatologo: string;
    sucursal: SucursalI;
    consecutivo: Number;
    pagado: Boolean;
    precio: string;
    total: string;
    materiales: [];
    toxinas_rellenos: [];
    status: StatusI;
    servicio: ServicioI;
    pagos: PagoI[];
    factura: FacturaI;
    observaciones: string;
    hora_llegada: string;
    hora_atencion: string;
    hora_salida: string;
    producto: ProductoI[];
    frecuencia: FrecuenciaI;
    total_aplicacion: string;
    porcentaje_descuento_clinica: string;
    has_descuento_dermatologo: Boolean;
    descuento_clinica: string;
    descuento_dermatologo: string;
    forma_pago: FormaPagoI;
    medio: MedioI;
    turno: string;
}